version: '3.9'

services:
  db:
    image: postgres:16
    environment: 
      POSTGRES_USER: denis
      POSTGRES_PASSWORD: NewPassword
      POSTGRES_DB: einkaufsliste-app
    volumes:
      - db_data:/var/lib/postgresql/data

    ports: 
      - "5432:5432"

  adminer:
    image: adminer
    depends_on:
         - db
    ports:
        - "8081:8080"

volumes:
  db_data:

